print("                                               ")
print("                                               ")
print("                                               ")
print("                                               ")
print("                                               ")
print("                                               ")
print("                                               ")
print("                                               ")
print("╔════════════════════════════════════╦════════╗")
print("║  ████ ███ ███   ██ ███ ██████ █  █ ║  V 2.2 ║")
print("║  █     █  █ █   ██  █  █      █  █ ║CREATIVE║")
print("║  ██    █  █  █  ██  █   ███   ████ ║   HD   ║")
print("║  █     █  █   █ ██  █      ██ █  █ ╠════════╣")
print("║ A█C  T███I█   V███ ███E██████H█ D█ ║ FINISH ║")
print("╚════════════════════════════════════╩════════╝")
print("                                   CREATIVE-HD.")
print("                                               ")
print("                                               ")
print("      ปิด TERMUX แล้วเปิดใหม่เพื่อให้ระบบ AUTO ทำงาน       ")
print("                                               ")
print("                                               ")
print("                                               ")
print("                                               ")
print("                                               ")
print("                                               ")
print("                                               ")
print("                                               ")
print("                                               ")
    
