print(" ╔════════════════════════════════════╦════════╗")
print(" ║    ████ ████ █████ █ █    ██ █████ ║  V 2.5 ║")
print(" ║   ██  █ █      █   █ █   ██        ║CREATIVE║")
print(" ║  ██ ███ █      █   █ █  ██   ███   ║   HD   ║")
print(" ║ ██    █ █      █   █ █ ██          ╠════════╣")
print(" ║██    A█C████  T█  I█V███    E█████ ║ START. ║")
print(" ╚════════════════════════════════════╩════════╝")
print("------------------------------------------------")
print("Development AMS by CREATIVE-HD")
print("------------------------------------------------")
print("                   ACTIVE MODE")
print("    ▝  ▘ ")
print(" █ ███████ █     TERMUX AUTO START ")
print(" █ █ 2.2 █ █ CCMINER AFTER BOOT DEVICE")
print("   ███████       RUNNING AUTOMATIC")
print("    ██ ██                             AUG.2025  ")
print("------------------------------------------------")    

